name: Publish Model

on:
  push:
    branches: [ "main" ]
    paths:
      - "artifacts/**/*.pt"
      - "src/deploy/**"
      - "src/streamlit_app.py"
  workflow_dispatch:

jobs:
  test-train-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .

    - name: Pytest
      run: |
        pytest

    - name: Model Validation
      run: |
        echo "To add performance validation before deploy"

    - name: Docker Build and Push
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: lequan2902/vaegan
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
